fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    stdlib:  'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    registry: 'https://github.com/puppetlabs/puppetlabs-registry.git'
    provision: 'https://github.com/puppetlabs/provision.git'
