name 'badgerious-puppet_env'
version '1.0.0'
summary 'Manages Windows environment variables'
description 'Create, delete, and insert values into Windows environment variables'
project_page 'https://github.com/badgerious/puppet-windows-env'
license 'Apache License, Version 2.0'
author 'badgerious'
